apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
        - name: python-api
          image: onlinetest.azurecr.io/azuretest/python_api    
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: 1500m
              memory: 3000Mi
            requests:
              cpu: 50m
              memory: 300Mi
      imagePullSecrets:
        - name: acrcred
---
apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  ports:
  - port: 80
  selector:
    app: python-api
