az_resource_name = "test-rg"
az_region = "North Europe"
aks_name = "api-test"
aks_agent_count = "2"
aks_vm_size = "Standard_DS2_v2"
az_service_principal_client_id = ""
az_service_principal_client_secret = ""
